[BE] APDS-6 - make intercom a standalone package
ArabellaTech/aa-intercom pull request #1
Opened 2017-05-26 16:45 UTC by poxip

2017-05-26 19:57 UTC, remik requested changes
Please use `master` as main branch. We don't use git flow for libraries.

2017-05-26 19:57 UTC, remik commented on LICENSE
> +Copyright (c) 2016 Arabella
It is 2017 already.

2017-05-26 19:57 UTC, remik commented on README.rst
> +  INTERCOM_ID_PREFIX = ""
I think prefix is not credentials but some of our settings.

2017-05-26 19:57 UTC, remik commented on aa_intercom/management/commands/update_intercom_users.py
> +        # return  # not sure if it is not needed. Commenting out for now to check.
??

2017-05-26 19:57 UTC, remik commented on aa_intercom/migrations/0002_auto_20170224_1455.py
> +# -*- coding: utf-8 -*-
Can we have only 1 migration before release?

2017-05-26 19:57 UTC, remik commented on aa_intercom/models.py
> +        Fill types per project.
This is not abstract so how we can fill it? Probably types should be in settings.

2017-05-26 19:57 UTC, remik commented on requirements/requirements-base.txt
> +python-intercom==3.1.0
Do not freeze version in libraries

2017-05-26 19:57 UTC, remik commented on setup.py
> +    url="https://github.com/ArabellaTech/aa_intercom",
typo

2017-05-26 19:57 UTC, remik commented on README.rst
> +  INTERCOM_APP_ID = "app id"
It is not used.

2017-05-26 19:57 UTC, remik commented on aa_intercom/admin.py
> +class IntercomEventAdmin(admin.ModelAdmin):
This should be read only.

2017-05-26 19:57 UTC, remik commented on README.rst
> +Django integration for Intercom_ API
Please describe what is it doing and how to use it. We can use it for more the user model, right?

2017-05-29 08:00 UTC, poxip commented on aa_intercom/management/commands/update_intercom_users.py
> +        # return  # not sure if it is not needed. Commenting out for now to check.
That's old @jacoor's code. @jacoor should we drop it?

2017-05-29 09:17 UTC, jacoor requested changes

2017-05-29 09:17 UTC, jacoor commented on README.rst
> +  INTERCOM_API_ACCESS_TOKEN = "your access key"
access token not key

2017-05-29 09:17 UTC, jacoor commented on aa_intercom/management/commands/update_intercom_users.py
> +        # return  # not sure if it is not needed. Commenting out for now to check.
@poxip please drop it completely.

2017-05-29 09:17 UTC, jacoor commented on aa_intercom/migrations/0002_auto_20170224_1455.py
> +# -*- coding: utf-8 -*-
+1. Please remove all migrations and rerun migrate to have only one.

2017-05-29 09:17 UTC, jacoor commented on aa_intercom/utils.py
> +    """Creates or updates single user account on intercom
Please move it to new line, alignt with """ or move to one line w/o spaces between. """ and text.

2017-05-29 09:17 UTC, jacoor commented on test_project/urls.py
> +The `urlpatterns` list routes URLs to views. For more information please see:
Do we really need this comment?

2017-05-29 09:17 UTC, jacoor commented on test_project/wsgi.py
> +WSGI config for test_project project.
As above, do we need this comment?

2017-05-29 09:20 UTC, poxip commented on aa_intercom/management/commands/update_intercom_users.py
> +        # return  # not sure if it is not needed. Commenting out for now to check.
Ok

2017-05-31 22:04 UTC, remik approved these changes

2017-06-01 08:18 UTC, jacoor approved these changes

2017-06-01 08:51 UTC, merged