[BE] APDS-43 - add metadata field to IntercomEvent
ArabellaTech/aa-intercom pull request #2
Opened 2017-06-07 09:09 UTC by poxip

2017-06-07 09:24 UTC, jacoor commented
@poxip can you increase coverage?

2017-06-08 18:47 UTC, poxip commented
Covered most of the gaps with tests.

2017-06-08 22:40 UTC, jacoor requested changes
Overall it looks good, minor updates to documentation and comments.
Good job!

2017-06-08 22:40 UTC, jacoor commented on README.rst
> +Anoter step is to add event types to project settings, for example:
settings file. In line 40 you use "settings file", here you refer to project settings. Please make it consistent.

2017-06-08 22:40 UTC, jacoor commented on README.rst
>      content_type=Post, object_id=post.id)
what's this Post in content_type? where is get_contenttype_for_model?

2017-06-08 22:40 UTC, jacoor commented on README.rst
> +Then it will be automatically sent to the Intercom API.
using post save signal.
You are missing information about "resend_intercom_events" cron job here.

2017-06-08 22:40 UTC, jacoor commented on README.rst
> +Then it will be automatically sent to the Intercom API.
I see it below in commands, but it would be good also to mention here. Intercom API goes down frequently.

2017-06-08 22:40 UTC, jacoor commented on aa_intercom/models.py
> +    metadata = JSONField()
help_text or maybe link to intercom docs?

2017-06-08 22:40 UTC, jacoor commented on aa_intercom/tests/test_commands.py
>          # Disable post_save signal during the test
Add why.

2017-06-08 22:40 UTC, jacoor commented on test_project/settings.py
> +    ("generic type", _("Generic Type"))
hmm. I've seen "generic" only somewhere above.
aa_intercom/tests/test_commands.py L18 and readme. 
Please just update here go simply "generic" and "example"

2017-06-12 10:11 UTC, jacoor requested changes

2017-06-12 10:11 UTC, jacoor commented on README.rst
>      content_type=Post, object_id=post.id)
@poxip  still, POST is something wrong. Where is get_contenttype_for_model?

2017-06-12 10:15 UTC, merged